### ISSUE TITLE
Dump old flag logs to the Feedback table and manually annotate feedback_label from the feedback_text where the feedback_label is null in the logs

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#101]

**Comment by mihaivavram** [comment]
Possible feedback_labels are:

- Human
- Bot
- Cyborg (human using, e.g. a scheduler)
- Organization

**Comment by clayadavis** [comment]
Above are the human-readable versions. The db labels should be

    human, bot, cyborg, org

https://github.iu.edu/Botometer/botometer-website/blob/95758e8234fc8785b37119e3239880eff809aeaa/app/main/main.html#L239-L242

**Comment by clayadavis** [comment]
It seems like I forgot to tag the new feedback with "type": "flag". Check out this log I created: https://pastebin.com/7RF20tQ5

Luckily there is still plenty of ways to identify these such as the presence of the "feedback" or "flag_type" properties.

**Comment by clayadavis** [comment]
Add a column to this db that stores the "source" user id.

**Comment by mihaivavram** [comment]
I have added the source id column, and also noticed that there are two new types of flag logs (at least) one that starts with feedback and one that starts with source. The one that has the feedback object is the one that you just pointed me to, so thank you I'll use that to add it to the logs, and I'm guessing any other type such as source doesn't have any text/label so we shouldn't add these to the feedback table right?

 `{"feedback": {"classification_text":, `{"source": {"follow_request_sent":`

**Comment by clayadavis** [comment]
The website tracks 3 types of flags. The first is from the form, which has
the "feedback" property and "flag_type": "form". But we also collect flags
when someone blocks or unfollows another user from our interface. These
don't have the "feedback" property, but have "flag_type": "block" or
"unfollow", respectively.

For all of these, the source is the logged-in user, and the target is the
user whose bot score is being shown.

I guess we should also add the "block" and "unfollow" flags. Probably do
this by inserting the row with a "block" or "unfollow" classification, and
blank text.

**Comment by clayadavis** [comment]
Sorry this got kinda complicated, I added these features by request but
since we haven't gone back and looked at them yet I'd kinda forgotten I did
it.

**Comment by mihaivavram** [comment]
No worries @clayadavis I created a new script to handle these three cases and it seems to work. Few questoins though:

1) Which one is the target_profile we are looking to store, it is the "target" json object from the line right?
2) We will eventually have to write a method to store these feedback records directly to the database instead of the logs right? If so I will just upload up to a certain recent point, then when we decide to push this change I can upload some of the last logged cases.

**Comment by clayadavis** [comment]
Yes and yes.

**Comment by mihaivavram** [comment]
Uploaded all of the feedback logs up until and including the 08-13-2017 log file.

**Comment by clayadavis** [comment]
Clayton Davis wants to start a conversation with you on Glip

**Comment by clayadavis** [comment]
Reminder: OMG Sorry wants to start a conversation with you on Glip
