### ISSUE TITLE
Create CRON job acting on Feedback table that fetches profile (user object), mentions_timeline, or user_timeline from Twitter if in any case it is null (every 20 min)

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#102]

**Comment by mihaivavram** [comment]
@clayadavis Hey Clayton, for creating this CRON job, I am thinking of a process that kicks off a Python script that runs every 15 minutes and checks for any `null profiles`, `mentions_timelines`, or `user_timelines` in the `feedback` table, then executes some Twitter Dev code to retain this information via the Twitter Ads API and [Python API](https://github.com/twitterdev/twitter-python-ads-sdk/). However, I think this process entails me creating a new Twitter App, applying for access (which also needs approval), and then using my secret key in the script. Should I be doing this, or do we have another tool/account to make this process easier?

Also, feel free to change/edit anything here if my judgment is incorrect.

**Comment by mihaivavram** [comment]
@clayadavis I am using the following Twitter API endpoints:

User Profile: [users/lookup](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-lookup) 
User Timeline: [statuses/user_timeline](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline)
User Mentions: [statuses/mentions_timeline](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-mentions_timeline)

And I am retrieving the latest 200 posts in both the timeline and mentions. Seeing as how you have experience with where to retrieve this from the Twitter API, this all sounds correct right?

**Comment by clayadavis** [comment]
It's preferable to use the search API instead of mentions_timeline to
retrieve mentions, for ratelimit reasons. We retrieve 200 tweets from
user_timeline and 100 tweets searching for the user screen name.

**Comment by mihaivavram** [comment]
@clayadavis Hmm, I'm not quite understanding. Are you talking about the [users/search](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-search) endpoint? Also when you say "100 tweets searching for the user screen name" is this referring to mentions or something else altogether?

**Comment by clayadavis** [comment]
I mean the [search/tweets endpoint](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets). You can get 200 tweets from a single user/timeline request, and 100 tweets from a single search request. The search we're doing is the user's screen name. To be clear, this is convoluted and not as good as the mentions timeline, but the mentions timeline has a very low ratelimit.

**Comment by mihaivavram** [comment]
I see. Indeed statuses/mentions_timeline only has 75 requests per 15 minutes, while the other endpoints you mention have 900 for statuses/user_timeline and 180 for search/tweets. Though the Cron job sends 10 requests every 10 minutes at most (top 10 query). I don't expect the feedback table to fill up so fast to the point where we will be surpassing 75 requests per 15 minutes, so I am erring on the side of keeping the code as is.

However, if you think I should change it to the preferred method, I can do this as well. You can make the call :)

**Comment by clayadavis** [comment]
Why reinvent the wheel? Just use https://github.com/IUNetSci/botometer-python

**Comment by mihaivavram** [comment]
Thank you, I used a similar approach with tweepy.
