### ISSUE TITLE
Talk about Feedback Table

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-botometer#13]

**Comment by filmenczer** [comment]
This is the feedback from users about actions that they take such as unfollowing and blocking. And use this data to retrain the model.

**Comment by mihaivavram** [comment]
Discussed Table Schema:

user_id bigint NOT NULL,
screen_name character varying(15),
time_stamp timestamp with time zone DEFAULT now(),
feedback_label character varying (50),
feedback_text text,
profile jsonb,
timeline_tweets jsonb,
mention_tweets jsonb
