### ISSUE TITLE
Issue: Top articles stats page is broken on online version (investigate why and hopefully fix this)

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#136]

**Comment by mihaivavram** [comment]
Chengcheng's words:

`The database part is OK. I restarted the backend service and now it is running well now. The gunicorn log shows that there was an invalid query in the API part and the roll back not called, which block any following query. I believe this is a bug that I do not handle well when sqlalchemy exception happens, I mark this as the to do job.`

**Comment by mihaivavram** [comment]
Chengcheng's words:

`The database part is OK. I restarted the backend service and now it is running well now. The gunicorn log shows that there was an invalid query in the API part and the roll back not called, which block any following query. I believe this is a bug that I do not handle well when sqlalchemy exception happens, I mark this as the to do job.`

**Comment by benabus** [comment]
All dashboard lists are working correctly.
