### ISSUE TITLE
Outreach on launch

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#140]
Upon launch contact:
* [x] Josh Stearns
* [x] ONA FB page on data journalism --- Meghan Murphy <meghan@journalists.org> could put in touch with ONA lists (see email from Jan 17)
* [ ] NICAR listserv
* [x] FirstDraft
* [x] Facebook literacy page
* [x] fakenewsci
* [x] pfgn (Lewandoski)
* [x] disinfo Google Group by NED
* [x] tech & check (Adair)
* [x] Various reporters (Fil *and* Kevin)
* [x] social media
* [x] SOCNET

**Comment by filmenczer** [comment]
* ONA FB page on data journalism
* NICAR listserv
* FirstDraft
* Facebook literacy page
* fakenewsci
* posttruth network of Lewandoski
* disinfo Google Group by NED

**Comment by filmenczer** [comment]
Launch is on Thursday. @glciampaglia and Fil to do outreach on Wed.

**Comment by glciampaglia** [comment]
No news about NICAR subscription. Closing for now. Will check it off in case I do get approved.
