### ISSUE TITLE
Create a first-time video for new version of Hoaxy site/Graph

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#141]
See [Hamilton68](http://dashboard.securingdemocracy.org/) as an example of this

**Comment by mihaivavram** [comment]
We discussed the issue, and we decided that instead of the walk-through we will have a video.  The video will auto-play for first-time users and have nice music.

**Comment by benabus** [comment]
Non issue.  We're now using a slide show introduction
