### ISSUE TITLE
Migrate the botometer database to Lenny

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#143]
* [x] @clayadavis to follow up with Rob to install postgres on Lenny
* [x] We will test migration of botomoter to see if performance improves or degrades. If it improves, we may move Botomoter and then we might also look at Hoaxy. 
* [x] Lenny will need to be backed up (currently it is not).
* [ ] If we decide instead to stick with recall, we will need to pay to purchase the extra disks

**Comment by glciampaglia** [comment]
@yangkcatiu will __copy__ (NOT move) the botometer database to run the test

**Comment by mihaivavram** [comment]
Moved to Lenny as the performance is better and we have full control of database tuning and bandwidth of the server.
