### ISSUE TITLE
Upload failback logs to botscore table from db failure of 10/31/2017

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#145]

**Comment by mihaivavram** [comment]
@clayadavis I notice that some botscore logs have a screen-name prefixed with the `@` symbol, and for some maxed-out screen names i.e. 15 characters + `@` this becomes 16 and breaks the db constraint of 15 characters for screen name. A lot of these longs have been failing and going to the failback logs. At first I thought I should increase the constraint to 16, but then I realized that Kevin's API may do a search on a strict screen name without the `@` symbol, so I think we should have screen_names that don't have any `@` prefixed. So this should be fixed on the botometer API side I believe (which you have completed recently). 

You can go ahead and fix it or please point me to where you made the change so I can take care of it. Thanks!

Best,
Mihai

**Comment by clayadavis** [comment]
This is fixed. We'll have to remember to strip any '@' from screen names when inserting these logs into the db.

**Comment by clayadavis** [comment]
For the sake of having it here, carl's version of botometer-server has a [nice function](https://github.iu.edu/Botometer/botometer-server/blob/carl/botometer_server/app.py#L380-L392) for inserting dicts as db rows. This can probably be used with slight modification for this task.

**Comment by mihaivavram** [comment]
@clayadavis Thank you, I borrowed some functionality from that function; however, I ran into some problems with the dynamically created placeholders given our feedback/botscore logs, which forced me to manually create the scripts. This is all fine, and completed ;)
