### ISSUE TITLE
Develop API that will allow users to query botometer cache through REST endpoint

### ISSUE THREAD

**Issue by benabus** [IUNetSci/hoaxy-botometer#15]
API will be written using python and [Flask](http://flask.pocoo.org/)

**Comment by benabus** [comment]
api will not interact with botometer directly.  It will only need to read from database. Querying botometer will happen client side.  

Will need 2 query parameter types:  /api/scores?userIDs=xxx,xxx,xxx,xxx and /api/scores?usernames=xxx,xxx,xxx,xxx

Will need to accept POST requests as well as GET because it may exceed the 2000 character limit imposed on GET requests.

Will need to implement the first part of the caching diagram... checking for age of latest score.

Will need to return JSON.   Should return 3 types of results:  username and score (if score exists and is fresh enough), username and null score (if username is not in database), or username and score and 'old' flag (if the username is in the cache, but is too old).

**Comment by filmenczer** [comment]
I think we decided the API needs to implement most of the caching diagram -- checking not only age but possibly also number of requests. And also increment the number of requests.

**Comment by yangkcatiu** [comment]
@filmenczer Please check the apidev for the newly redrawn flow chart for API.

**Comment by benabus** [comment]
@filmenczer I think @yangkcatiu is referring to https://github.com/IUNetSci/hoaxy-botometer/blob/apidev/backend/API/API_flow_chart.pdf
