### ISSUE TITLE
Make sure Google Analytics tracking code is included in new version; add hook to collect Twitter search queries

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#151]
Currently Hoaxy uses Google Analytics to collect the queries made by users. We have to make sure that the new version uses the same tracking code, and that the hook for the queries works also for the Twitter search.

**Comment by mihaivavram** [comment]
The title of this issue is not informative enough, we must give more details about it before it can be discussed.

**Comment by benabus** [comment]
Google analytics code is added to the demo site.
