### ISSUE TITLE
Wrong article dates in search results

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-botometer#163]
Search results display the current date instead of the publishing date. Compare these results from Hoaxy: 
![selection_999 008](https://user-images.githubusercontent.com/1506860/34354691-6c0ba0a2-ea30-11e7-8005-2cb35790a454.png) 

with these from Hoaxy Botomoter: 

![selection_999 013](https://user-images.githubusercontent.com/1506860/34354696-74ab8c2c-ea30-11e7-93d2-3bd3493891ed.png)

This is likely something @benabus can take care of, so I am assigning him directly. Please reassign if this should be somebody else's task.

**Comment by benabus** [comment]
This has been resolved.  Used wrong attribute name.
