### ISSUE TITLE
Add (Top Claims, Top Fact-Checks, and Top Headlines) to the Hoaxy landing page after the first Search/Visualize button

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#171]
Have these as an extra dashboard from which the user can search directly using our tool given top/relevant/popular articles and posts.

The Top Fact-Checks, and Top Claims can already be retrieved from the Dashboard page and perhaps Cheng Cheng knows of the code/script to generate such metrics.

The Top Headlines, Mihai will write a CRON job to retrieve them and write them to a flat file.

Each of these three columns should include x amount of entries as rows and each entry should look like the following:

```
<Article Name>
Source: <Source of article>
```

Where the `<Article Name>` can be clicked and when it is, the search box can be populated with the text. Furthermore, the Source: (NOT `<Source>`) can be clicked and that should populate the search box with the url of the article.

**Comment by benabus** [comment]
Also see https://github.com/IUNetSci/hoaxy-botometer/issues/137

**Comment by mihaivavram** [comment]
Almost done, we just now need to think about where to run the cron job, where the .json lies, and other configuration changes to "hook it up" but once hooked up it works.
