### ISSUE TITLE
UI fixes and improvements

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-botometer#175]
These things came as we gave the presentation for the Knight Foundation folks:
* [ ] Display query as title in the visualization screen
* [ ] Add label "Select area of interest" in the time diagram and move up the chart  
* [ ] "Fork me on Github" ribbon is broken?
* [ ] Footer does not position correctly?
* [ ] "Source" -> "Code" or "Software"
* [ ] When you click "Stop" it should reset the full animation
* [ ] Make a toggle with Play and Pause button
* [ ] Create walk-through presentation and replace video intro (BIG issue)
* [ ] Do we want to allow users to provide feedback on the bot score of disabled/deactivated Twitter accounts?

**Comment by glciampaglia** [comment]
@mihaivavram please reorganize these into individual issues.

**Comment by mihaivavram** [comment]
We can keep this issue open until we have discussed the contents. Once we have discussed and altered the tasks at hand, we can close this organizational issue out.

**Comment by mihaivavram** [comment]
We have added all of these issues independently and discussed them at length.
