### ISSUE TITLE
Restructure Interface for Hoaxy search

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#195]
- [x] Automatically Select First Result
- [x] Automatically scroll to visualization
- [x] Add button for expanding the search called "Expand Search" that goes to the Hoaxy result list
- [x] Remove the pulsing animation on the buttons
- [x] Remove share buttons from list and put share in visualizations
- [x] Consider whether to put search list above or below the visualizations

**Comment by benabus** [comment]
Reworked the structure to emphasize the visualization aspect of the project.
