### ISSUE TITLE
Create a tutorial for the Hoaxy-Botometer tool

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#204]

**Comment by mihaivavram** [comment]
The following components can be included in the tutorial:
- create this as a cartoon, in top panel (button) and use cookies to show tutorial or not
- 1st page search box/dashboard
- 2nd visualization
- 3rd select sources
- Be able to scroll between them 

- use cookies

**Comment by benabus** [comment]
Tutorial is now a set of 5 slides done in a semi-abstract style with callouts to the various features in the interface.  The tutorial displays upon loading the Hoaxy site and can be hidden on subsequent visits using a cookie.
