### ISSUE TITLE
Change Twitter screen-names to ids in APIs that contact the database or any servers to optimize database queries

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#218]

**Comment by benabus** [comment]
Requests to the Botometer database uses a set of IDs instead of Screen names.

**Comment by clayadavis** [comment]
This was a good move. The `userid_timestamp` index is 30% smaller than the `screenname_timestamp` index, and will thus be able to be kept in memory that much longer.
