### ISSUE TITLE
Integrate the new Botometer

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-botometer#227]
We will adjust the color scale and the node pop-up based on the new scores or probability. We will link to the details screen on Botometer from there.

**Comment by filmenczer** [comment]
The API will return both the new (calibrated) bot score as a float in [0,1] using the same field name, and the new Bayesian posterior probability as a new field.

The interface will show the probability as a %age, and the score on a scale [0,5], like this: 1.7/5 or 2.0/5 (using fixed precision). This will also match the 5 colors in the legend.

**Comment by glciampaglia** [comment]
In the frontend, we the user clicks on a node, we need to add a link to the Botometer query for that account. The page should open in a new tab or window. The page will show the bot probability and other details. The URL for this page is `https://botometer.iuni.iu.edu/#!/?sn=<SCREEN_NAME>`.

@clayadavis will see if it is possible to show the results pane already expanded.

**Comment by clayadavis** [comment]
> The page will show the bot probability and other details. The URL for this page is https://botometer.iuni.iu.edu/#!/?sn=<SCREEN_NAME>.

Done. Is that the last thing we needed?

**Comment by filmenczer** [comment]
There is the issue of expanding the pane when one gets to the page using the URL https://botometer.iuni.iu.edu/#!/?sn=<SCREEN_NAME>

And also updating the Botometer FAQ

**Comment by clayadavis** [comment]
The pane should expand. It's possible you have an old version of the Botomter site code. The FAQ is its own issue in the botometer-website repo.

**Comment by clayadavis** [comment]
@mihaivavram, you shouldn't need to update the API to do anything. The calibrated scores are where the old, raw scores used to be. There is that issue about the cache, marking old scores as stale.

**Comment by filmenczer** [comment]
Yes, I force-reloaded and the auto-expansion works! 
And I see some bright colors popping up... 
So I guess this issue can be closed.

**Comment by clayadavis** [comment]
There were some browser-specific issues with the auto-scrolling to the expanded score, but those have now also been fixed.

**Comment by filmenczer** [comment]
Assuming this can be closed? Thanks!
