### ISSUE TITLE
Change logging in Botometer to send directly to database

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-botometer#23]
Botometer will be the only source for updating/inserting scores in the database.

**Comment by mihaivavram** [comment]
@clayadavis Do you mind leading me to the repo/codebase that we must make this change in? Is it [here](https://github.com/IUNetSci/botometer-python)? Also, should I just pull the repo, and make proper changes testing them in my own dev environment, then push to the origin remote once everything is working. This is the process right, or am I missing something?

**Comment by clayadavis** [comment]
The repo you linked to is the Python API for using Botometer. I invited you to the team with access to the Botometer server code. It's sensitive, so I won't link here.

**Comment by mihaivavram** [comment]
Script is almost completed, passing it on to Clayton to add the finishing touches.

**Comment by mihaivavram** [comment]
@clayadavis Please let me know once you're ready to deploy this and once you are I can upload all of the remaining logs to the botscore database.

**Comment by clayadavis** [comment]
Will do. I should get to this in the next couple of days.

**Comment by glciampaglia** [comment]
We discussed the issue today during our weekly meeting and decided that we must make sure that the bot score object is also stored in the database. We need another JSON field in the DB @mihaivavram.

**Comment by clayadavis** [comment]
This is close to done. Is everything ready on the database @mihaivavram ?

**Comment by mihaivavram** [comment]
@clayadavis the short answer to this is - as ready as it can be.

The long answer is - I have recently updated the feedback and botscore tables up to log `botornot.log.2017-10-15` which includes all logs up to date `10-22-2017`, the rest of the logs are still accumulating in the `/home/data/apps/BotOrNot/logs/botornot.log` file until it gets written to another file I believe on the 29th so this Sunday and it will be called `botornot.log.2017-22-2017`. 

It is difficult, unless you completely stop the file logging process or change the logging stream to another file to seamlessly connect the stream of log+direct insertion to the database, but I think what you can do is right before the start the automatic flow of logging to the database, you can record the time-stamps (beginning time, end time) of the logs that are in the interim (not yet manually added to the database) then we can manually add those later as we store the time-stamp so it doesn't matter what sequence they are added in as long as they are added.

Let me know if this makes sense or if you need anything else from me. If you need to manually upload logs, just see my `/u/truthy/mihai-hoaxybotometer/feedbackinsertion/UploadNewFeedbackLogsToBotometer.py' (for feedback logs) and `/u/truthy/mihai-hoaxybotometer/loginsertion/UploadLogsToBotbase.py` (for botscore logs)

**Comment by clayadavis** [comment]
This is working. We should finish inserting the logs and also investigate missing logs.

**Comment by clayadavis** [comment]
There are a bunch of logs in `/home/data/apps/BotOrNot/logs` that hadn't been moved to `/l/cnets/...` yet. Not sure if you saw them. Once you load them up, you/we can move them to the folder on `/l/cnets`.
