### ISSUE TITLE
Improve hourglass

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-botometer#231]
The animation is obscured by it!

**Comment by benabus** [comment]
Remove the hourglass while the graph is animating.

**Comment by filmenczer** [comment]
If removing the hourglass during network layout creates problems, then make it smaller and move it down.

**Comment by glciampaglia** [comment]
@benabus will move it back to the center, as it now it disappears for the layout, and it works great.

**Comment by benabus** [comment]
Moves hourglass back to center.
