### ISSUE TITLE
Color scale should show bin counts of bot score distribution

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-botometer#235]

**Comment by filmenczer** [comment]
A simpler way to capture this would be a number next to each shade of color.
We also discussed an alternative approach with a control where the user would set the probability threshold between blue/red.

**Comment by clayadavis** [comment]
We're just going to do the simple thing and show the number by the color bins, and ditch the user control.

**Comment by glciampaglia** [comment]
@mihaivavram will fix the legend text and will close.

**Comment by mihaivavram** [comment]
The request written by glciampaglia has been completed. Closing.

**Comment by filmenczer** [comment]
Could we please make it not bold? None of the other interface elements use bold font.

**Comment by mihaivavram** [comment]
Ok, I did both, let's see how it looks at the meeting.

**Comment by glciampaglia** [comment]
Looks great!
