### ISSUE TITLE
Visualize larger networks

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-botometer#238]
Currently we apply k-core decomposition until the network is below a certain size (I think 1000 nodes). 

However, this often produces odd results, like with this query on [White Helmets](http://iuni.iu.edu/hoaxy-botometer-demo/#query=white%20helmets&sort=relevant&type=Hoaxy) --- there are more than 1,100 tweets, and yet the k-core produces only a handful of nodes. 

Now that the backend is much faster, why not increasing the limit to 2000 nodes, or even something higher?

**Comment by benabus** [comment]
Decided to go into backend code and change the kcore filtering to sort by core . number, then take the top 1000 nodes.

**Comment by glciampaglia** [comment]
This has been fixed. It turns out that the code was already doing what we wanted, but it was affected by a bug that would remove nodes even when the network was within the limit. I have reimplemented the function in a less confusing way: https://github.com/IUNetSci/hoaxy-backend/commit/09d67388967ea9474f01a5a6cd2f3d82f622fba3

Code pushed in production and tested. It works now!
