### ISSUE TITLE
Remove 20 limit for visualizing articles.

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-botometer#239]
If one loads more than 20 articles, there is no way to select them all at once. The checkbox that will select the top 20 article does not change behavior when more than 20 articles are loaded. I think it should. This is not a bug per se since the interface is not misleading, but it would be still helpful to change its behavior. 

To reproduce the problem:
1. Run any query
2. Click on '1 article visualized'
3. Scroll down the list, and click 'load more articles'
4. Scroll up again, and click 'Select Top 20'
5. It will only select the top 20 articles, leaving unselected the bottom 20.

**Comment by benabus** [comment]
This was by design.  I think it had to do with performance on the backend.


Ben Serrette
Web Developer
Indiana University Network Science Institute

**Comment by glciampaglia** [comment]
Makes sense. Now that the backend is not a bottleneck anymore we may reconsider it. I have marked it for discussion for the next meeting.

**Comment by benabus** [comment]
Remove limit for only being able to visualize 20 articles.
