### ISSUE TITLE
Allow to search for URLs in Hoaxy mode

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-botometer#244]
When searching for a URL (eg, one of the URLs in the dashboard) using Hoaxy search, the top article selected by default is NOT necessarily the one with the queried URL. This is a problem as it is misleading to the user. Can this be fixed?

**Comment by glciampaglia** [comment]
As far as I remember (and @shaochengcheng please correct me if I'm wrong), the URL was never an indexed field in Lucene. I think the only fields we used were the contents of the `<TITLE></TITLE>` tag, and the article body. 

I have tried to search by URL in the past, and sometimes it works and sometimes it doesn't. 

I think that what is happening is that somehow Lucene is able to treat parts of the URL as if they were keywords. We would need to see if we can add the URLs as a field to the index.

**Comment by filmenczer** [comment]
Unless we can add this functionality in a very short time (I doubt it), I think we should remove the "Search Link" altogether (at least in Hoaxy search). It is misleading. The search by title should work as intended.

For Twitter search, I think it should be okay to keep both.

**Comment by filmenczer** [comment]
@mihaivavram, could you please remove the "Search Link" links just under "Popular Claims" and "Popular Fact-Checks" in the homepage dashboard? Thanks!

**Comment by mihaivavram** [comment]
No problem, I will do this.

**Comment by mihaivavram** [comment]
Request from @filmenczer is done, removing this from Launch and adding to Utopia.

**Comment by glciampaglia** [comment]
This issue was moved to IUNetSci/hoaxy-frontend#10
