### ISSUE TITLE
Tweak node details pop-up modal

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-botometer#249]
* [x] Colored background only around Score ~~and the icons~~
* [x] Bigger font for the first sentence and the "details" link
* [x] Two buttons should have same size and same font, and the labels should be: "Update" and "Feedback"

**Comment by filmenczer** [comment]
Actually the part with the color background should be only the score number (eg, 2.3/5), and NOT include the bird icons. With some background colors (eg blue) the icons look ugly and are hard to see. So the icons, together with everything else (text above, text below and buttons) should have transparent or white background.

**Comment by mihaivavram** [comment]
All done including Fil's suggestions. Closing.
