### ISSUE TITLE
Two search interface issues

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-botometer#252]
First Scenario:
1. Do a search using Hoaxy
2. Modify the query in the search box above the visualization
3. Hit enter

Result: the query switches to Twitter search type. It should not -- it should use the selected type. (It works okay if you click the search button, the problem is only when pressing enter)

Second Scenario:
1. Do a search using Hoaxy
2. Modify the query in the search box above the visualization
3. Click the 'Twitter' button

Result: the search is launched without clicking search or hitting enter. This might be okay if the user did not change the query, but is unexpected after a query change. Let's just disable this functionality -- one must click search.

**Comment by benabus** [comment]
Fixed.  Both of these were the results of a bug in how the form was submitting.
