### ISSUE TITLE
Stats pages still using percentages for bot scores

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-botometer#253]
These still show the bot scores as a percentage:

http://iuni.iu.edu/hoaxy-botometer-demo/stats.html#influential_users
http://iuni.iu.edu/hoaxy-botometer-demo/stats.html#active_users

They should show scores on the 5-point scale, per consensus to move away from bot score percentages.

**Comment by glciampaglia** [comment]
Adding @shaochengcheng to coordinate in case the cron job needs to be changed.

**Comment by benabus** [comment]
Fixed.  Now uses 5 point scale.
