### ISSUE TITLE
Long term solution for the Botometer database API is needed

### ISSUE THREAD

**Issue by yangkcatiu** [IUNetSci/hoaxy-botometer#256]
Currently the API is public. It prevents the requests from other people by checking the 'origin' and 'referer' in the http/s header. There are two downsides about this solution: 1. it's not perfectly safe, people with web knowledge can still find a way to bypass the check 2. it's getting harder to manage due the different ways handling the request of different browsers. A long term solution is needed.

Possible solutions are:
1. Putting the API on mashape. It could the right way to go if one day we want to make the database public, but it could also add overhead and slow down the response time
2. Add a filter on the Apache site on Carl. It could make the logics of the API easier.

**Comment by glciampaglia** [comment]
We discussed the issue and @clayadavis suggests to configure Apache on the Hoaxy vhost in a way similar to the Botometer vhost. Instead of blacklisting, we should whitelist the domain `hoaxy.iuni.iu.edu`.
