### ISSUE TITLE
Run log upload script on production database

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#40]

**Comment by mihaivavram** [comment]
Here are some minor issues I've been running into when attempting to run the script in the production server:

1. The logs are stored on Carl but we should not be running any computationally intensive job on Carl because that's where the CNetS website is running, instead we should be running the script on Burns I think, but then we will need to copy the logs to Burns. @clayadavis do you agree? If so where on Burns can we store the logs? 
2. I am using the Python psycopg2 adapter to upload data to Postgres, but this library is not available on Burns/Carl... @clayadavis are we allowed to install it with pip install or do we have to submit a ticket? Or should we use some other way/adapter?

**Comment by mihaivavram** [comment]
The approach here is to run each log one by one, assessing output from the script, and if there are any discrepancies, we must revert, fix any discrepancies, and insert the given log again.

**Comment by clayadavis** [comment]
> The logs are stored on Carl but we should not be running any computationally intensive job on Carl because that's where the CNetS website is running, instead we should be running the script on Burns I think, but then we will need to copy the logs to Burns. @clayadavis do you agree? If so where on Burns can we store the logs?

Being a single process, I don't think resources are going to be an issue. Just use [`nice`](https://www.gnu.org/software/coreutils/manual/html_node/nice-invocation.html) for a long-running script.

> I am using the Python psycopg2 adapter to upload data to Postgres, but this library is not available on Burns/Carl... @clayadavis are we allowed to install it with pip install or do we have to submit a ticket? Or should we use some other way/adapter?

Don't bother with adding packages to the system Python install; it's old and a hassle. The easiest way around this is to use `pip install --user` a la https://stackoverflow.com/a/7143496

**Comment by mihaivavram** [comment]
Currently running each incremental log file by file (around 100-500 MB) of records at a time, and checking the results of the [validation script](https://github.com/IUNetSci/hoaxy-botometer/blob/backend-database-dev/backend/tools/oldloginsertion/post_insert_validation_script.sql) to check for discrepancies then continuing as to ensure there is no missed data or wrongly-inserted records.
