### ISSUE TITLE
Change upload-script error logging to only include proper records insertion failures, and not the other informational data in the old logs

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#50]

**Comment by mihaivavram** [comment]
Some screen-names from the logs are not present, meaning that the screen-name that is retrieved is the user-id which can be larger than 14 characters in length. When we created the database the schema constrained the screen-name to 14 characters in length (as the maximum size from Twitter of any screen-name has this limitation). What should we do in this case? My current solution is to not change the database schema, and instead just not include the screen-name if it is the same as the user-id. This seems okay but then there could be problems if there really ARE screen-names now or in the future with more than 14 characters in length. What do you think @clayadavis ? How should we proceed?

**Comment by clayadavis** [comment]
Twitter doesn't allow screen names longer than 15 characters. In the case where there is no screen name in the logs, then either put NULL there or an empty string, whatever's easier (the equivalence coming from the fact that an empty string is obviously not a real screen name). If Twitter changes their 15-character limit in the future, one can easily alter that schema constraint. That being said, the 15-character limit on that column just serves as a sanity check to alert you of cases like the one you bring up. If it's more headache than it's worth, then scrap it. There's no technical reason for the limit.

But on to the situation at hand. Now that you mention it, I do recall the old logs allowing for the situation you mention where user id and screen name are confused; I had to change how that was logged to disallow this situation. Do whatever you want to do here. If the logged "screen name" is longer than 15 characters and is all digits, then it's really a user id and should be logged as such. In the situation where you only have the screen name and the screen name is entirely numeric, you can just assume it's a misplaced user id.

The numbers of entries affected by this are likely small compared to the data size, so it's not a big deal what you decide. When in doubt, do the easy thing.

**Comment by mihaivavram** [comment]
The way this discrepancy was fixed was with the following condition:

```
                if len(screen_name) > 15:
                    #user may have a screen-name logged as longer than 15 characters which is not proper in Twitter and could be instead the userid or some other error so we make it none
                    screen_name = None

```

**Comment by mihaivavram** [comment]
So far, the json types that are present are `log`, `flag`, and `exception` and hence we only want to keep the `log` types.

**Comment by clayadavis** [comment]
When you're seeing `screen_name` longer than 15 characters, is there always a `user_id` along with it?

> So far, the json types that are present are log, flag, and exception and hence we only want to keep the log types.

:+1:
