### ISSUE TITLE
Determine Server that will be used to host DB

### ISSUE THREAD

**Issue by benabus** [IUNetSci/hoaxy-botometer#6]
We need to choose a hosting location.  Likely one of the Informatics servers.

**Comment by benabus** [comment]
Trying to set up a new database on recall.ils.indiana.edu.  This may cause problems with connection rate limits.  If it doesn't work out, we'll set up something on burns.

**Comment by mihaivavram** [comment]
Currently database is set up on recall.ils.indiana.edu, if we need to change this we can re-open this issue.

Furthermore, we can log-in using a <user_name> with the following command from a SICE server such as Carl or Burns via: `psql -U <user_name> -d <db_name> -h recall.ils.indiana.edu -p 5433`
