### ISSUE TITLE
Change database schema on table-create script to reflect Issue #81: https://github.com/IUNetSci/hoaxy-botometer/issues/81

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#78]
@clayadavis There is one more field in the db schema called num_mentions, I assume this also falls in the same bucket of being personal information about the user which we shouldn't store? So should I remove that as well?

**Comment by mihaivavram** [comment]
@yangkcatiu I'm adding this so we can co-ordinate this shift as the API will need to change once I update the db schema. Though you can just look [here](https://github.com/IUNetSci/hoaxy-botometer/blob/backend-database-dev/backend/database/CreateTablesScript.sql) to anticipate the changes as I have already pushed them to my test environment and branch, just haven't pushed them to the ILS database yet.

**Comment by yangkcatiu** [comment]
@mihaivavram I checked the changes, I should be easy to modify to API.

- [ ] Remove or rename the `num_tweets` field from the SQL queries(4 locations)
- [ ] If `num_tweets` removed, change the index of `num_requests` from 9 to 8
